version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
      - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" 
      - echo "$CODEBUILD_WEBHOOK_PREV_COMMIT" 
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "composer install"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
