version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
      # - type -p yum-config-manager >/dev/null || yum install yum-utils
      - yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
      - yum install gh
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "composer install"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
