version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
      - echo Installing GitHub CLI
      # - yum install -y curl
      - curl -LJO https://github.com/cli/cli/releases/latest/download/gh_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.tar.gz
      - tar xvf gh_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.tar.gz --strip-components=1 -C /usr/local/bin/

  pre_build:
    commands:
      - echo "pre build"
      - gh pr diff $CODEBUILD_RESOLVED_SOURCE_VERSION --name-only
  build:
    commands:
      - echo "composer install"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
