version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
      - if [ `uname -m` = "x86_64" ]; then ARCH=amd64; else ARCH=arm64; fi
      - GH_CLI_VERSION=$(curl --silent "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
      - curl -LJO "https://github.com/cli/cli/releases/download/${GH_CLI_VERSION}/gh_${GH_CLI_VERSION}_linux_${ARCH}.tar.gz"
      - tar xvf gh_${GH_CLI_VERSION}_linux_${ARCH}.tar.gz -C /usr/local/bin/ --strip-components=1

  pre_build:
    commands:
      - echo "pre build"
      - gh pr diff $CODEBUILD_RESOLVED_SOURCE_VERSION --name-only
  build:
    commands:
      - echo "composer install"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
