version: 0.2

env:
  shell: bash
  git-credential-helper: yes
phases:
  install:
    commands:
      - echo "install step"

  pre_build:
    commands:
      - echo "pre build"
      - ls -lah
      - sudo yum install git -q -y
      - git --version
      - TICKETS_LIST=$(git log origin/ai-initiative --no-merges --pretty=format:"%B" --not "origin/master" | tr a-z A-Z | tr ' ,' '\n' | grep -o '[A-Z]\+-[0-9]\+' | sort --version-sort | uniq | tr '\n' ',')
      - echo $TICKETS_LIST
      - echo "commit test"
  build:
    commands:
      - echo "composer install"
      - echo "drush commands test"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
