version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
      - echo Installing GitHub CLI
      - curl -O -L https://github.com/cli/cli/releases/latest/download/gh_linux_amd64.deb
      - dpkg -i gh_linux_amd64.deb
  pre_build:
    commands:
      - echo "pre build"
      - gh pr diff $CODEBUILD_RESOLVED_SOURCE_VERSION --name-only
  build:
    commands:
      - echo "composer install"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
