version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
      - curl -sSL https://github.com/cli/cli/releases/download/v2.29.0/gh_2.29.0_linux_amd64.tar.gz
      - tar -xf gh_2.29.0_linux_amd64.tar.gz
      - mv gh_2.29.0_linux_amd64/bin/gh /usr/local/bin/

  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "composer install"
      - echo "drush commands"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
