version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "pre build"
      - |
        for file in "$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_WEBHOOK_PREV_COMMIT)"; do
            # Process each line of the output here
            echo "File: $file"
        done
  build:
    commands:
      - echo "composer install"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
