version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"

  pre_build:
    commands:
      - echo "pre build"
      - TICKETS_LIST=$(git log origin/develop --no-merges --pretty=format:"%B" --not "origin/staging" | tr a-z A-Z | tr ' ,' '\n' | grep -o '[A-Z]\+-[0-9]\+' | sort --version-sort | uniq | tr '\n' ',')
      - echo $TICKETS_LIST
  build:
    commands:
      - echo "composer install"
      - echo "drush commands"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
