version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "install step"
      - curl -sSL https://github.com/cli/cli/releases/latest/download/gh_linux_amd64.tar.gz | tar xz -C /tmp
      - mv /tmp/gh_*_linux_amd64/bin/gh /usr/local/bin/

  pre_build:
    commands:
      - echo "pre build"
      - gh pr diff $CODEBUILD_RESOLVED_SOURCE_VERSION --name-only
  build:
    commands:
      - echo "composer install"
  post_build:
    commands:
      - echo "Zip the report"
    finally:
      - echo "Remove all containers"
